# Generated by Django 3.1 on 2020-09-07 15:33

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='bloguser',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮件地址'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. ', verbose_name='激活状态'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='管理员权限'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='username',
            field=models.CharField(help_text='Required. 100 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=100, unique=True, validators=[blog.models.UnicodeUsernameValidator()], verbose_name='用户名'),
        ),
    ]
