# Generated by Django 3.1 on 2020-09-08 12:18

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200907_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='description',
            field=models.TextField(null=True, verbose_name='用户描述'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='icon',
            field=models.URLField(null=True, verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='username',
            field=models.CharField(help_text='Required. 100 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
