# Generated by Django 3.1 on 2020-09-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200909_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='use_sum',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.category'),
        ),
    ]
