# Generated by Django 3.1 on 2020-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200908_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='display_account',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
