# Generated by Django 3.1 on 2020-09-08 13:02

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200908_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮件地址'),
        ),
    ]
