# Generated by Django 3.1 on 2020-09-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200910_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-datetime_created']},
        ),
    ]
