# Generated by Django 3.1 on 2020-09-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200910_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
    ]
