# Generated by Django 3.1 on 2020-09-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200911_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datetime_noticed',
            field=models.DateTimeField(null=True, verbose_name='通知时间'),
        ),
    ]
