# Generated by Django 3.1.2 on 2020-10-20 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201019_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=36, null=True)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='web_tickets', related_query_name='web_ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
