# Generated by Django 3.1.2 on 2020-12-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201201_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='info',
            field=models.JSONField(help_text='额外信息', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='datetime_update',
            field=models.DateTimeField(auto_now=True, help_text='修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_status',
            field=models.BooleanField(db_index=True, default=False, help_text='发布状态'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='文章标题', max_length=150),
        ),
        migrations.AlterField(
            model_name='articleimages',
            name='image',
            field=models.URLField(help_text='文章图片'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='目录', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(help_text='评论内容', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='receivemessage',
            name='datetime_send',
            field=models.DateTimeField(auto_now_add=True, help_text='发送时间'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.CharField(help_text='回复内容', max_length=200),
        ),
        migrations.AlterField(
            model_name='reply',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='datetime_noticed',
            field=models.DateTimeField(help_text='通知时间', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.URLField(help_text='用户头像', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='手机号', max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(help_text='验证码', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='datetime_sent',
            field=models.DateTimeField(help_text='发送时间', null=True),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='phone',
            field=models.CharField(help_text='手机号', max_length=11),
        ),
    ]
