# Generated by Django 3.1 on 2020-09-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_id', models.IntegerField(verbose_name='附属ID')),
                ('attached_table', models.CharField(max_length=20, verbose_name='附属表')),
                ('image', models.URLField(verbose_name='文章图片')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'index_together': {('attached_id', 'attached_table')},
            },
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
