# Generated by Django 3.1 on 2020-09-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200924_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(max_length=6, null=True, verbose_name='验证码'),
        ),
    ]
