# Generated by Django 3.1 on 2020-10-14 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200924_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='发送内容')),
                ('datetime_send', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('send_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_messages', related_query_name='send_message', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receive_messages', related_query_name='receive_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
