# Generated by Django 3.1 on 2020-10-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_receivemessage'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='attachedpicture',
            index_together={('attached_id', 'attached_table', 'status')},
        ),
    ]
