# Generated by Django 3.1.2 on 2020-10-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201020_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websocketticket',
            name='ticket',
            field=models.CharField(max_length=32),
        ),
    ]
