# Generated by Django 3.1.2 on 2020-10-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201020_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websocketticket',
            name='ticket',
            field=models.CharField(max_length=36),
        ),
    ]
