# Generated by Django 3.1.2 on 2020-10-24 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201020_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='文章图片')),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('article', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='blog.article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AttachedPicture',
        ),
    ]
