# Generated by Django 3.1.2 on 2020-10-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201024_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookUpValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommend', to='blog.article')),
                ('comment', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommend', to='blog.comment')),
            ],
        ),
        migrations.CreateModel(
            name='LookUpKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Look_up_value', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='value', to='blog.lookupvalue')),
            ],
        ),
    ]
