# Generated by Django 3.1.2 on 2020-10-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201026_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='Look_up_value',
            new_name='recommend_info',
        ),
    ]
