# Generated by Django 3.1.2 on 2020-10-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_article_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='object_id',
        ),
        migrations.AddField(
            model_name='article',
            name='object',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.activity'),
        ),
    ]
