# Generated by Django 3.1.2 on 2020-10-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201027_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='object',
        ),
    ]
