# Generated by Django 3.1.2 on 2020-10-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20201028_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=1, verbose_name='内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='datetime_update',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_status',
            field=models.BooleanField(default=False, verbose_name='发布状态'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(max_length=30, null=True, verbose_name='标签'),
        ),
        migrations.DeleteModel(
            name='ArticleInfo',
        ),
    ]
