# Generated by Django 3.1.2 on 2020-11-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20201116_1142'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articleimages',
            table='blog_article_images',
        ),
    ]
