# Generated by Django 3.1.2 on 2020-12-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20201201_1120'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verifycode',
            table='blog_verify_code',
        ),
    ]
