# Generated by Django 3.1.2 on 2020-12-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20201201_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagship',
            unique_together={('article', 'tag')},
        ),
    ]
