# Generated by Django 3.1.4 on 2020-12-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20201201_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='info',
            field=models.JSONField(null=True),
        ),
    ]
