# Generated by Django 3.1 on 2020-09-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_status',
            field=models.BooleanField(default=False, verbose_name='发布状态'),
        ),
    ]
